### PR TITLE
Fixed other plugins cancelling the chat event still processing chat h…

### PR DESCRIPTION
**Pull request by OmerBenGera**
…andlers

### CODE REVIEW

**Comment by TheBusyBiscuit** [comment]
Could you please elaborate on what exact issue this is supposed to fix?
I am not really sure where this change is coming from since there is no description to this Pull Request.

But anyway, I am skeptical at this change and whether changing the existing failsafe to a fail-unsafe is the right approach to this.
Because if another plugin cancels this Event, then the Player will remain inside that HashMap of callbacks indefinitely, potentially queuing up more and more until the server's memory gets polluted.
I do think this queue must be resolved in some shape or form to prevent this pollution from happening.

Under normal circumstances, this event is only ever called after the User has been explicitly prompted to enter text via chat.
So I can also see how this will result in numerous bug reports about all plugins using this no longer working with chat input as it gets overridden and cancels by other plugins.

I would be very grateful if you could share your thoughts on why you think this change is needed, what issue you were trying to fix and why you think this is the right approach.

**Comment by OmerBenGera** [comment]
> 
> 
> Could you please elaborate on what exact issue this is supposed to fix?
> I am not really sure where this change is coming from since there is no description to this Pull Request.
> 
> But anyway, I am skeptical at this change and whether changing the existing failsafe to a fail-unsafe is the right approach to this.
> Because if another plugin cancels this Event, then the Player will remain inside that HashMap of callbacks indefinitely, potentially queuing up more and more until the server's memory gets polluted.
> I do think this queue must be resolved in some shape or form to prevent this pollution from happening.
> 
> Under normal circumstances, this event is only ever called after the User has been explicitly prompted to enter text via chat.
> So I can also see how this will result in numerous bug reports about all plugins using this no longer working with chat input as it gets overridden and cancels by other plugins.
> 
> I would be very grateful if you could share your thoughts on why you think this change is needed, what issue you were trying to fix and why you think this is the right approach.

The commit description describes itself. When another plugin is canceling the event, you shouldn't process it. For example, I have a team-chat system in one of my plugins, which processes the chat handling on its own. Because you don't check for canceled events, then they conflict with each other.
If you are worried about players to stay inside your maps, then you'll probably need to think about another way to cache them or something... or, the bug will still occur

**Comment by WalshyDev** [comment]
How is CS-CoreLib2 not getting this event if cancelled gonna fix this issue? You know that the issue is that your plugin posts in chat when someone runs our command right?

(Also, sidenote, this is LOWEST priority, very little could cancel before we get it anyway so this will have barely any impact).

**Comment by TheBusyBiscuit** [comment]
Again: Could you please elaborate on what "bug" you are talking about?
And why you think a fail-unsafe is more practical in this scenario?

I am sorry but it doesn't seem like you seem to follow.
As I explained earlier: This event is only called when a plugin **explicitly** requests chat input, so this - at least  how I see it - should definitely have priority over any chat plugin, as this is not an actual chat message but rather a user-input prompt.
I think this change would really just break more than it would fix.

**Comment by OmerBenGera** [comment]
> 
> 
> How is CS-CoreLib2 not getting this event if cancelled gonna fix this issue? You know that the issue is that your plugin posts in chat when someone runs our command right?
> 
> (Also, sidenote, this is LOWEST priority, very little could cancel before we get it anyway so this will have barely any impact).

I am making sure that the event is canceled befure I process anything, and it still processing. It's probably due to my plugin running before yours, so it should be fixed.
I'll try changing priorities, even tho that's not a good approach, but I don't see anybody here that actually willing to do something. This issue will still happen with other plugins that also listen to chat in LOWEST priority, and it should be fixed on your end.

**Comment by J3fftw1** [comment]
Strange thing is when you are in admin chat of towny and you do the sf search there is no chat output , it just opens the sf guide with the searched item. Admin chat from towny is also something similar to your skyblock chat

**Comment by OmerBenGera** [comment]
> 
> 
> Strange thing is when you are in admin chat of towny and you do the sf search there is no chat output , it just opens the sf guide with the searched item. Admin chat from towny is also something similar to your skyblock chat

Probably because they are using different priorities. Nothing to do with the fact that it's a bug that can occur

**Comment by TheBusyBiscuit** [comment]
> it's a bug that can occur

I have already asked you twice to elaborate on what issue you are referring to.
What is happening, what is not happening, what did you expect to happen?
And why do you think this would be the right approach?
As I also asked twice before: Why do you think the fail-unsafe should be preferred over the the fail-safe?

So far you haven't answered a single question I asked, I really wanted this to be a constructive discussion as I have no idea what you are even referring to here due the lack of context and description.

Also: Are you aware of what this code does and how it works? It's fine, if not but please allow me to explain it then if something is unclear about it.

**Comment by OmerBenGera** [comment]
> 
> 
> > it's a bug that can occur
> 
> I have already asked you twice to elaborate on what issue you are referring to.
> What is happening, what is not happening, what did you expect to happen?
> And why do you think this would be the right approach?
> As I also asked twice before: Why do you think the fail-unsafe should be preferred over the the fail-safe?
> 
> So far you haven't answered a single question I asked, I really wanted this to be a constructive discussion as I have no idea what you are even referring to here due the lack of context and description.
> 
> Also: Are you aware of what this code does and how it works? It's fine, if not but please allow me to explain it then if something is unclear about it.

Every plugin that will run before yours and will cancel the event, your code will still work, therefore can get some weird things to happen (in my example, it was that writing in team chat caused the search handler to still work). A simple fix for that is to ignore events that were already canceled.

**Comment by TheBusyBiscuit** [comment]
But that would result in chat handlers no longer working.
As I explained before: chat handlers are explicit prompts. I will try to give you an example.

For example in [Slimefun](https://github.com/TheBusyBiscuit/Slimefun4) we use this feature, so that when a user clicks the "search" button, it asks them "What do you want to search for?", the user proceeds by typing their answer in chat and the search results get listed.

Interrupting this flow and making it actually display in chat instead of continuing on with the code will cause more issues than it would really "fix" here. I hope this example illustrates better why I think this is not a good approach.
Because this event never gets called unless explicitly provoked by the user themselves anyway.

**Comment by OmerBenGera** [comment]
> 
> 
> But that would result in chat handlers no longer working.
> As I explained before: chat handlers are explicit prompts. I will try to give you an example.
> 
> For example in [Slimefun](https://github.com/TheBusyBiscuit/Slimefun4) we use this feature, so that when a user clicks the "search" button, it asks them "What do you want to search for?", the user proceeds by typing their answer in chat and the search results get listed.
> 
> Interrupting this flow and making it actually display in chat instead of continuing on with the code will cause more issues than it would really "fix" here. I hope this example illustrates better why I think this is not a good approach.
> Because this event never gets called unless explicitly provoked by the user themselves anyway.

I really don't understand the issue, but if you want to keep it like that - keep it.
It will happen with other plugins probably, so take that in mind.

**Comment by WalshyDev** [comment]
Something to state, a chat plugin should **not** be handling at LOWEST level and definitely should not be cancelling here. Other plugins should have their chance of also modifying chat some. In this rare event we should be the ones handling this, hence why it shouldn't be ignored.

I'd take a look at your code or even PR but paid private plugins :^)

Yours is the only plugin that's ever had an issue with this might I also add. None of the much larger plugins have or even smaller plugins.

**Comment by OmerBenGera** [comment]
> 
> 
> Something to state, a chat plugin should **not** be handling at LOWEST level and definitely should not be cancelling here. Other plugins should have their chance of also modifying chat some. In this rare event we should be the ones handling this, hence why it shouldn't be ignored.
> 
> I'd take a look at your code or even PR but paid private plugins :^)
> 
> Yours is the only plugin that's ever had an issue with this might I also add. None of the much larger plugins have or even smaller plugins.

There's no reason for other chat plugins to process their things if I will just erase their changes and handle it myself - right? There was a reason for it being on the LOWEST priority. Also, it doesn't matter if no one else had had this issue before, as it exists and I gave you an example. Again, if you don't want to fix it, then don't - I don't mind. It's not my plugin.
I changed my priority to LOW, I hope it won't cause issues with other plugins.
This issue is closed, so there's really no need to keep replying to this. Thanks.

**Pull request closed without merging**
